---

- name: Configure Service Namespaces
  include_tasks: configure_namespaces.yml
  vars:
    prefix: "{{ configured_service_spaces.prefix }}"
    quotas:
      compute_requests: "{{space.service_quotas.compute_requests}}" #"{{ service_spaces.(service_quotas | default({})).(compute_requests | default({})) | default(space.service_quotas.compute_requests) }}"
      compute_limits: "{{space.service_quotas.compute_limits}}" #"{{ service_spaces.(service_quotas | default({})).(compute_limits | default({})) | default(space.service_quotas.compute_limits) }}"
      storage: "{{space.service_quotas.storage}}" # "{{ service_spaces.(service_quotas | default({})).(storage | default({})) | default(space.service_quotas.storage) }}"
      object_count: "{{space.service_quotas.object_count}}" #"{{ service_spaces.(service_quotas | default({})).(object_count | default({})) | default(space.service_quotas.object_count) }}"
  with_items:
    - "{{ configured_service_spaces.spaces }}"
  loop_control:
    loop_var: space

- name: Configure Shared Namespaces
  include_tasks: configure_namespaces.yml
  vars:
    prefix: "{{ configured_shared_spaces.prefix }}"
    quotas: "{{ configured_shared_spaces.service_quotas }}"
  with_items:
    - "{{ configured_shared_spaces.spaces }}"
  loop_control:
    loop_var: space

- name: Configure User Namespaces
  include_tasks: configure_namespaces.yml
  vars:
    prefix: "{{ configured_user_spaces.prefix }}"
    quotas: "{{ configured_user_spaces.service_quotas }}"
  with_items:
    - "{{ configured_user_spaces.spaces }}"
  loop_control:
    loop_var: space