---

service_spaces: []
shared_spaces: []
user_spaces: []

configured_service_spaces:
  service_quotas:
    compute_requests:
      requests_cpu: 1
      requests_memory: 1
      requests_storage: 0
      requests_ephemeral-storage: 0
    compute_limits:
      limits_cpu: 1
      limits_memory: 1
      limits_storage: 0
      limits_ephemeral-storage: 0
    storage_limits:
      requests: 0
      persistent_volume_claims: 4
      ephemeral_storage_requests: 100
      ephemeral_storage_limits: 200
    object_count_limits:
      loadbalancers: 5
      nodeports: 0
      configmaps: 10
      pods: 4
      replicationcontrollers: 20
      secrets: 10
  prefix: svc
  spaces:
    - "{{ service_spaces }}"

configured_shared_spaces:
  service_quotas:
    compute_requests:
      requests_cpu: 1
      requests_memory: 1
      requests_storage: 0
      requests_ephemeral-storage: 0
    compute_limits:
      limits_cpu: 1
      limits_memory: 1
      limits_storage: 0
      limits_ephemeral-storage: 0
    storage_limits:
      requests: 0
      persistent_volume_claims: 4
      ephemeral_storage_requests: 100
      ephemeral_storage_limits: 200
    object_count_limits:
      loadbalancers: 5
      nodeports: 0
      configmaps: 10
      pods: 4
      replicationcontrollers: 20
      secrets: 10
  prefix: shd
  spaces:
    - "{{ shared_spaces }}"

configured_user_spaces:
  service_quotas:
    compute_requests:
      requests_cpu: 1
      requests_memory: 1
      requests_storage: 0
      requests_ephemeral-storage: 0
    compute_limits:
      limits_cpu: 1
      limits_memory: 1
      limits_storage: 0
      limits_ephemeral-storage: 0
    storage_limits:
      requests: 0
      persistent_volume_claims: 4
      ephemeral_storage_requests: 100
      ephemeral_storage_limits: 200
    object_count_limits:
      loadbalancers: 5
      nodeports: 0
      configmaps: 10
      pods: 4
      replicationcontrollers: 20
      secrets: 10
  prefix: usr
  spaces: 
    - "{{ user_spaces }}"